services:
  postgres-db:
    container_name: profile-matcher_db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres-user
      POSTGRES_PASSWORD: postgres-pass
      POSTGRES_DB: postgres
    volumes:
      - "C:/local-postgres-db:/var/lib/postgresql/data"
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4-app
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"
    volumes:
      - "C:/local-pgadmin:/var/lib/pgadmin"
