services:
  profile-matcher:
    image: profile-matcher:latest
    ports:
      - 8080:8080

  postgres-db:
    container_name: profile-matcher_db
    image: postgres:latest
    environment:
      POSTGRES_USER: super_admin
      POSTGRES_PASSWORD: SomeSecretPassword
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"